export const Images = {
  icons: {
    book: require('../assets/icons/book.png'),
    warning: require('../assets/icons/warning.png'),
    reports: require('../assets/icons/reports.png'),
    inspection: require('../assets/icons/inspection.png'),
    clock: require('../assets/icons/clock.png'),
  },
  bottomnavicons: {
    home: require('../assets/icons/home.png'),
    schedule: require('../assets/icons/schedule.png'),
    reports: require('../assets/icons/reports.png'),
    message: require('../assets/icons/message.png'),
    profile: require('../assets/icons/profile.png'),
  },
  reportscreen: {
    back: require('../assets/icons/back.png'),
    bell: require('../assets/icons/bell.png'),
    search: require('../assets/icons/search.png'),
    commercial: require('../assets/icons/commercial.png'),
    done: require('../assets/icons/done.png'),
    download: require('../assets/icons/download.png'),
    share: require('../assets/icons/share.png'),
    industrial: require('../assets/icons/industrial.png'),
    residental: require('../assets/icons/residental.png'),
    warehouse: require('../assets/icons/warehouse.png'),
    warn: require('../assets/icons/warn.png'),
    violation: require('../assets/icons/violation1.png'),
    pending: require('../assets/icons/pending.png'),
  },
  attachmentImage: {
    1: require('../assets/images/1.png'),
    2: require('../assets/images/2.png'),
    3: require('../assets/images/3.png'),
    4: require('../assets/images/4.png'),
    5: require('../assets/images/5.png'),
    6: require('../assets/images/6.png'),
  },
};
